app-config:
  kafka-config:
    bootstrap-servers: localhost:9092
    producer-config:
      acks-config: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer-config:
      auto-offset-reset: earliest
      group-id: foo
      client-id: foo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8083